import org.poomda.activity.ActivityType
import org.poomda.animal.Animal
import org.poomda.animal.AnimalBreed
import org.poomda.animal.AnimalType
import org.poomda.file.ImgAnimal
import org.poomda.file.ImgShelter
import org.poomda.locale.Address
import org.poomda.locale.Country
import org.poomda.member.Role
import org.poomda.member.User
import org.poomda.member.UserLikeAnimal
import org.poomda.member.UserRole
import org.poomda.shelter.Shelter


class BootStrap {

    def init = { servletContext ->
		
		User admin = new User(username:'admin@admin.com', password:'admin',age:27,phone:'line : licocy', nickname:'admin',profile:'/poomda/upload/member/profile_sample.png', enabled:true).save(failOnError:true)
		User manager = new User(username:'manager@manager.com', password:'manager', nickname:'manager', enabled:true).save(failOnError:true)
		User user = new User(username:'user@user.com', password:'user',  nickname:'개발자', ,age:27,phone:'line : licocy',profile:'/poomda/upload/member/profile_sample.png',enabled:true, gender:'남',birthday:new Date()-10000, introduction : '유저입니다.', activityHistory:'개발했어요').save(failOnError:true)
		
		def roleAdmin = Role.findOrSaveWhere(authority:"ROLE_ADMIN").save(failOnError:true)
		def roleManager = new Role(authority: 'ROLE_MANAGER').save(failOnError:true)
		def Role roleUser = new Role(authority: 'ROLE_USER').save(failOnError:true)
		
		UserRole.create admin, roleAdmin, true
		UserRole.create admin, roleUser, true
		UserRole.create manager, roleManager, true
		UserRole.create user, roleUser, true

		def at1 = new AnimalType(name:'dog',nameKor:'개',description:'baowao').save()
		def at2 = new AnimalType(name:'cat',nameKor:'고양이', description:'nio').save()
		
		def s1 = new Shelter(name:'남양주 보호소', address:'경기-남양주', user:admin, introduction:
			'경기도 남양주시에 위치하여 2011년부터 여러 봉사자들과 함께 동물들을 보호해 오고 있습니다. 강아지,고양이 합쳐서 100여마리 규모의 보호소 입니다.').save(failOnError:true)
		new ImgShelter(  shelter:s1, user : admin, filename:'shelter_sample.jpg',filepath:'/poomda/upload/shelter/', extention : 'jpg', status : 'INITIALIZE' ).save(failOnError:true)
		def s2 = new Shelter(name:'마석보호소', address:'마석', user:admin, introduction:
			'마석에 위치하여 2011년부터 여러 봉사자들과 함께 동물들을 보호해 오고 있습니다. 강아지,고양이 합쳐서 200여마리 규모의 보호소 입니다.').save(failOnError:true)
		new ImgShelter(  shelter:s2, user : admin, filename:'shelter_sample.jpg',filepath:'/poomda/upload/shelter/', extention : 'jpg', status : 'INITIALIZE' ).save(failOnError:true)
			
		new AnimalBreed(register:admin,animalType:at1,name:'골든 리트리버',nameKor:'골든 리트리버').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at1,name:'래브라도 리트리버',nameKor:'래브라도 리트리버').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at1,name:'도베르만',nameKor:'도베르만').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at1,name:'말티즈',nameKor:'말티즈').save(failOnError:true)
		def ab1 = new AnimalBreed(register:admin,animalType:at1,name:'말라뮤트',nameKor:'말라뮤트').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at1,name:'미니어처 닥스훈트',nameKor:'미니어처 닥스훈트').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at1,name:'비글',nameKor:'비글').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at1,name:'셰클랜드 십독',nameKor:'셰클랜드 십독').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at1,name:'시추',nameKor:'시추').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at1,name:'슈나우져',nameKor:'슈나우져').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at1,name:'아메리칸 코커 스파니엘',nameKor:'아메리칸 코커 스파니엘').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at1,name:'아프간 하운드',nameKor:'아프간 하운드').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at1,name:'와이어 폭스 테리어',nameKor:'와이어 폭스 테리어').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at1,name:'요크셔테리어',nameKor:'요크셔테리어').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at1,name:'이탈리안 그레이 하운드',nameKor:'이탈리안 그레이 하운드').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at1,name:'잉글리시 코커 스파니엘',nameKor:'잉글리시 코커 스파니엘').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at1,name:'웰시 코기 펨브로크',nameKor:'웰시 코기 펨브로크').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at1,name:'진돗개',nameKor:'진돗개').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at1,name:'치와와(롱코트)',nameKor:'치와와(롱코트)').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at1,name:'토이푸들',nameKor:'토이푸들').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at1,name:'파피용',nameKor:'파피용').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at1,name:'퍼그',nameKor:'퍼그').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at1,name:'포메라니안',nameKor:'포메라니안').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at1,name:'프렌치 불독',nameKor:'프렌치 불독').save(failOnError:true)
		
		
		new AnimalBreed(register:admin,animalType:at2,name:'페르시안',nameKor:'페르시안').save(failOnError:true)
		def ab2 = new AnimalBreed(register:admin,animalType:at2,name:'샴',nameKor:'샴').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'브리티시 쇼트',nameKor:'브리티시 쇼트').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'헤어',nameKor:'헤어').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'아비시니안',nameKor:'아비시니안').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'메인쿤',nameKor:'메인쿤').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'아메리칸 쇼트',nameKor:'아메리칸 쇼트').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'헤어',nameKor:'헤어').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'벵골',nameKor:'벵골').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'스핑크스',nameKor:'스핑크스').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'래그돌',nameKor:'래그돌').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'엑조틱 쇼트헤',nameKor:'엑조틱 쇼트헤').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'어',nameKor:'어').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'버미즈',nameKor:'버미즈').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'버먼',nameKor:'버먼').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'스코티시 폴드',nameKor:'스코티시 폴드').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'러시안 블루',nameKor:'러시안 블루').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'노르웨이숲',nameKor:'노르웨이숲').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'히말라얀',nameKor:'히말라얀').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'시베리안 고양',nameKor:'시베리안 고양').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'이',nameKor:'이').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'맹크스',nameKor:'맹크스').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'사바나',nameKor:'사바나').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'먼치킨',nameKor:'먼치킨').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'터키시 앙고라',nameKor:'터키시 앙고라').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'데본렉스',nameKor:'데본렉스').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'코니시 렉스',nameKor:'코니시 렉스').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'봄베이',nameKor:'봄베이').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'발리니즈',nameKor:'발리니즈').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'아메리칸 밥테',nameKor:'아메리칸 밥테').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'일',nameKor:'일').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'샤르트뢰',nameKor:'샤르트뢰').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'재패니즈밥테일',nameKor:'재패니즈밥테일').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'이집션 마우',nameKor:'이집션 마우').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'아메리칸 컬',nameKor:'아메리칸 컬').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'터키시 반',nameKor:'터키시 반').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'오시캣',nameKor:'오시캣').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'싱가푸라',nameKor:'싱가푸라').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'톤키니즈',nameKor:'톤키니즈').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'소말리 고양이',nameKor:'소말리 고양이').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'아메리칸 와이',nameKor:'아메리칸 와이').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'어헤어',nameKor:'어헤어').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'코랏',nameKor:'코랏').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'컬러포인트 숏',nameKor:'컬러포인트 숏').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'헤어',nameKor:'헤어').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'셀커크 렉스',nameKor:'셀커크 렉스').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'오리엔탈 쇼트',nameKor:'오리엔탈 쇼트').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'헤어',nameKor:'헤어').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'자바니즈',nameKor:'자바니즈').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'스노우슈',nameKor:'스노우슈').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'라가머핀',nameKor:'라가머핀').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'하바나 브라운',nameKor:'하바나 브라운').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'픽시 밥',nameKor:'픽시 밥').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'킴릭',nameKor:'킴릭').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'라팜',nameKor:'라팜').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'토이거',nameKor:'토이거').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'버밀라',nameKor:'버밀라').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'쵸시',nameKor:'쵸시').save(failOnError:true)
		new AnimalBreed(register:admin,animalType:at2,name:'네벨룽',nameKor:'네벨룽').save(failOnError:true)
		
		5.times{
			def temp_animal=new Animal(shelter:s1, name:'말라뮤트', user : admin, status : '개인보호중', breed:ab1, gender:'수컷', age:'2살', furColor:'실버그레이',feature:'꼬리에 까만 무늬 있음', weight:'1kg').save(failOnError:true)
			new ImgAnimal(  animal:temp_animal, user : user, filename:'animal_sample.jpg',filepath:'/poomda/upload/animal/', extention : 'jpg', status : 'INITIALIZE' ).save(failOnError:true)
		}
		def animal1 = new Animal(shelter:s2, name:'doggi', user : admin, status : '개인보호중', breed:ab1, gender:'수컷', age:'1살', furColor:'white',weight:'1kg').save(failOnError:true)
		def animal2 = new Animal(shelter:s2,name:'cathy', user : admin, status : '개인보호중', breed:ab2, gender:'암컷', age:'5개월', furColor:'black',weight:'1kg').save(failOnError:true)
		new Animal(name:'cathy', user : admin, status : '개인보호중', breed:ab2, gender:'암컷', age:'3개월', furColor:'점박이',weight:'1kg').save(failOnError:true)
		
		new UserLikeAnimal(user: admin, animal: animal1).save(failOnError:true)
		new UserLikeAnimal(user: manager, animal: animal1).save(failOnError:true)
		
		def country = new Country(name:'korea',language:'korean').save(failOnError:true)
		
		new Address(country:country, state:'서울',city:'강남구').save(failOnError:true)
		new Address(country:country, state:'서울',city:'강동구').save(failOnError:true)
		new Address(country:country, state:'서울',city:'강북구').save(failOnError:true)
		new Address(country:country, state:'서울',city:'강서구').save(failOnError:true)
		new Address(country:country, state:'서울',city:'관악구').save(failOnError:true)
		new Address(country:country, state:'서울',city:'광진구').save(failOnError:true)
		new Address(country:country, state:'서울',city:'구로구').save(failOnError:true)
		new Address(country:country, state:'서울',city:'금천구').save(failOnError:true)
		new Address(country:country, state:'서울',city:'노원구').save(failOnError:true)
		new Address(country:country, state:'서울',city:'도봉구').save(failOnError:true)
		new Address(country:country, state:'서울',city:'동대문구').save(failOnError:true)
		new Address(country:country, state:'서울',city:'동작구').save(failOnError:true)
		new Address(country:country, state:'서울',city:'마포구').save(failOnError:true)
		new Address(country:country, state:'서울',city:'서대문구').save(failOnError:true)
		new Address(country:country, state:'서울',city:'서초구').save(failOnError:true)
		new Address(country:country, state:'서울',city:'성동구').save(failOnError:true)
		new Address(country:country, state:'서울',city:'성북구').save(failOnError:true)
		new Address(country:country, state:'서울',city:'송파구').save(failOnError:true)
		new Address(country:country, state:'서울',city:'양천구').save(failOnError:true)
		new Address(country:country, state:'서울',city:'영등포구').save(failOnError:true)
		new Address(country:country, state:'서울',city:'용산구').save(failOnError:true)
		new Address(country:country, state:'서울',city:'은평구').save(failOnError:true)
		new Address(country:country, state:'서울',city:'종로구').save(failOnError:true)
		new Address(country:country, state:'서울',city:'중구').save(failOnError:true)
		new Address(country:country, state:'서울',city:'중랑구').save(failOnError:true)
		new Address(country:country, state:'부산',city:'강서구').save(failOnError:true)
		new Address(country:country, state:'부산',city:'금정구').save(failOnError:true)
		new Address(country:country, state:'부산',city:'남구').save(failOnError:true)
		new Address(country:country, state:'부산',city:'동구').save(failOnError:true)
		new Address(country:country, state:'부산',city:'동래구').save(failOnError:true)
		new Address(country:country, state:'부산',city:'부산진구').save(failOnError:true)
		new Address(country:country, state:'부산',city:'북구').save(failOnError:true)
		new Address(country:country, state:'부산',city:'사상구').save(failOnError:true)
		new Address(country:country, state:'부산',city:'사하구').save(failOnError:true)
		new Address(country:country, state:'부산',city:'서구').save(failOnError:true)
		new Address(country:country, state:'부산',city:'수영구').save(failOnError:true)
		new Address(country:country, state:'부산',city:'연제구').save(failOnError:true)
		new Address(country:country, state:'부산',city:'영도구').save(failOnError:true)
		new Address(country:country, state:'부산',city:'중구').save(failOnError:true)
		new Address(country:country, state:'부산',city:'해운대구').save(failOnError:true)
		new Address(country:country, state:'부산',city:'기장군').save(failOnError:true)
		new Address(country:country, state:'대구',city:'남구').save(failOnError:true)
		new Address(country:country, state:'대구',city:'달서구').save(failOnError:true)
		new Address(country:country, state:'대구',city:'동구').save(failOnError:true)
		new Address(country:country, state:'대구',city:'북구').save(failOnError:true)
		new Address(country:country, state:'대구',city:'서구').save(failOnError:true)
		new Address(country:country, state:'대구',city:'수성구').save(failOnError:true)
		new Address(country:country, state:'대구',city:'중구').save(failOnError:true)
		new Address(country:country, state:'대구',city:'달성군').save(failOnError:true)
		new Address(country:country, state:'인천',city:'계양구').save(failOnError:true)
		new Address(country:country, state:'인천',city:'남구').save(failOnError:true)
		new Address(country:country, state:'인천',city:'남동구').save(failOnError:true)
		new Address(country:country, state:'인천',city:'동구').save(failOnError:true)
		new Address(country:country, state:'인천',city:'부평구').save(failOnError:true)
		new Address(country:country, state:'인천',city:'서구').save(failOnError:true)
		new Address(country:country, state:'인천',city:'연수구').save(failOnError:true)
		new Address(country:country, state:'인천',city:'중구').save(failOnError:true)
		new Address(country:country, state:'인천',city:'강화군').save(failOnError:true)
		new Address(country:country, state:'인천',city:'옹진군').save(failOnError:true)
		new Address(country:country, state:'광주',city:'광산구').save(failOnError:true)
		new Address(country:country, state:'광주',city:'남구').save(failOnError:true)
		new Address(country:country, state:'광주',city:'동구').save(failOnError:true)
		new Address(country:country, state:'광주',city:'북구').save(failOnError:true)
		new Address(country:country, state:'광주',city:'서구').save(failOnError:true)
		new Address(country:country, state:'대전',city:'대덕구').save(failOnError:true)
		new Address(country:country, state:'대전',city:'동구').save(failOnError:true)
		new Address(country:country, state:'대전',city:'서구').save(failOnError:true)
		new Address(country:country, state:'대전',city:'유성구').save(failOnError:true)
		new Address(country:country, state:'대전',city:'중구').save(failOnError:true)
		new Address(country:country, state:'울산',city:'남구').save(failOnError:true)
		new Address(country:country, state:'울산',city:'동구').save(failOnError:true)
		new Address(country:country, state:'울산',city:'북구').save(failOnError:true)
		new Address(country:country, state:'울산',city:'중구').save(failOnError:true)
		new Address(country:country, state:'울산',city:'울주군').save(failOnError:true)
		new Address(country:country, state:'세종',city:'').save(failOnError:true)
		new Address(country:country, state:'강원',city:'강릉시').save(failOnError:true)
		new Address(country:country, state:'강원',city:'동해시').save(failOnError:true)
		new Address(country:country, state:'강원',city:'삼척시').save(failOnError:true)
		new Address(country:country, state:'강원',city:'속초시').save(failOnError:true)
		new Address(country:country, state:'강원',city:'원주시').save(failOnError:true)
		new Address(country:country, state:'강원',city:'춘천시').save(failOnError:true)
		new Address(country:country, state:'강원',city:'태백시').save(failOnError:true)
		new Address(country:country, state:'강원',city:'고성군').save(failOnError:true)
		new Address(country:country, state:'강원',city:'양구군').save(failOnError:true)
		new Address(country:country, state:'강원',city:'양양군').save(failOnError:true)
		new Address(country:country, state:'강원',city:'영월군').save(failOnError:true)
		new Address(country:country, state:'강원',city:'인제군').save(failOnError:true)
		new Address(country:country, state:'강원',city:'정선군').save(failOnError:true)
		new Address(country:country, state:'강원',city:'철원군').save(failOnError:true)
		new Address(country:country, state:'강원',city:'평창군').save(failOnError:true)
		new Address(country:country, state:'강원',city:'홍천군').save(failOnError:true)
		new Address(country:country, state:'강원',city:'화천군').save(failOnError:true)
		new Address(country:country, state:'강원',city:'횡성군').save(failOnError:true)
		new Address(country:country, state:'경기',city:'고양시 덕양구').save(failOnError:true)
		new Address(country:country, state:'경기',city:'고양시 일산동구').save(failOnError:true)
		new Address(country:country, state:'경기',city:'고양시 일산서구').save(failOnError:true)
		new Address(country:country, state:'경기',city:'과천시').save(failOnError:true)
		new Address(country:country, state:'경기',city:'광명시').save(failOnError:true)
		new Address(country:country, state:'경기',city:'광주시').save(failOnError:true)
		new Address(country:country, state:'경기',city:'구리시').save(failOnError:true)
		new Address(country:country, state:'경기',city:'군포시').save(failOnError:true)
		new Address(country:country, state:'경기',city:'김포시').save(failOnError:true)
		new Address(country:country, state:'경기',city:'남양주시').save(failOnError:true)
		new Address(country:country, state:'경기',city:'동두천시').save(failOnError:true)
		new Address(country:country, state:'경기',city:'부천시 소사구').save(failOnError:true)
		new Address(country:country, state:'경기',city:'부천시 오정구').save(failOnError:true)
		new Address(country:country, state:'경기',city:'부천시 원미구').save(failOnError:true)
		new Address(country:country, state:'경기',city:'성남시 분당구').save(failOnError:true)
		new Address(country:country, state:'경기',city:'성남시 수정구').save(failOnError:true)
		new Address(country:country, state:'경기',city:'성남시 중원구').save(failOnError:true)
		new Address(country:country, state:'경기',city:'수원시 권선구').save(failOnError:true)
		new Address(country:country, state:'경기',city:'수원시 영통구').save(failOnError:true)
		new Address(country:country, state:'경기',city:'수원시 장안구').save(failOnError:true)
		new Address(country:country, state:'경기',city:'수원시 팔달구').save(failOnError:true)
		new Address(country:country, state:'경기',city:'시흥시').save(failOnError:true)
		new Address(country:country, state:'경기',city:'안산시 단원구').save(failOnError:true)
		new Address(country:country, state:'경기',city:'안산시 상록구').save(failOnError:true)
		new Address(country:country, state:'경기',city:'안성시').save(failOnError:true)
		new Address(country:country, state:'경기',city:'안양시 동안구').save(failOnError:true)
		new Address(country:country, state:'경기',city:'안양시 만안구').save(failOnError:true)
		new Address(country:country, state:'경기',city:'양주시').save(failOnError:true)
		new Address(country:country, state:'경기',city:'오산시').save(failOnError:true)
		new Address(country:country, state:'경기',city:'용인시 기흥구').save(failOnError:true)
		new Address(country:country, state:'경기',city:'용인시 수지구').save(failOnError:true)
		new Address(country:country, state:'경기',city:'용인시 처인구').save(failOnError:true)
		new Address(country:country, state:'경기',city:'의왕시').save(failOnError:true)
		new Address(country:country, state:'경기',city:'의정부시').save(failOnError:true)
		new Address(country:country, state:'경기',city:'이천시').save(failOnError:true)
		new Address(country:country, state:'경기',city:'파주시').save(failOnError:true)
		new Address(country:country, state:'경기',city:'평택시').save(failOnError:true)
		new Address(country:country, state:'경기',city:'포천시').save(failOnError:true)
		new Address(country:country, state:'경기',city:'하남시').save(failOnError:true)
		new Address(country:country, state:'경기',city:'화성시').save(failOnError:true)
		new Address(country:country, state:'경기',city:'가평군').save(failOnError:true)
		new Address(country:country, state:'경기',city:'양평군').save(failOnError:true)
		new Address(country:country, state:'경기',city:'여주군').save(failOnError:true)
		new Address(country:country, state:'경기',city:'연천군').save(failOnError:true)
		new Address(country:country, state:'경남',city:'거제시').save(failOnError:true)
		new Address(country:country, state:'경남',city:'김해시').save(failOnError:true)
		new Address(country:country, state:'경남',city:'밀양시').save(failOnError:true)
		new Address(country:country, state:'경남',city:'사천시').save(failOnError:true)
		new Address(country:country, state:'경남',city:'양산시').save(failOnError:true)
		new Address(country:country, state:'경남',city:'진주시').save(failOnError:true)
		new Address(country:country, state:'경남',city:'창원시 마산합포구').save(failOnError:true)
		new Address(country:country, state:'경남',city:'창원시 마산회원구').save(failOnError:true)
		new Address(country:country, state:'경남',city:'창원시 성산구').save(failOnError:true)
		new Address(country:country, state:'경남',city:'창원시 의창구').save(failOnError:true)
		new Address(country:country, state:'경남',city:'창원시 진해구').save(failOnError:true)
		new Address(country:country, state:'경남',city:'통영시').save(failOnError:true)
		new Address(country:country, state:'경남',city:'거창군').save(failOnError:true)
		new Address(country:country, state:'경남',city:'고성군').save(failOnError:true)
		new Address(country:country, state:'경남',city:'남해군').save(failOnError:true)
		new Address(country:country, state:'경남',city:'산청군').save(failOnError:true)
		new Address(country:country, state:'경남',city:'의령군').save(failOnError:true)
		new Address(country:country, state:'경남',city:'창녕군').save(failOnError:true)
		new Address(country:country, state:'경남',city:'하동군').save(failOnError:true)
		new Address(country:country, state:'경남',city:'함안군').save(failOnError:true)
		new Address(country:country, state:'경남',city:'함양군').save(failOnError:true)
		new Address(country:country, state:'경남',city:'합천군').save(failOnError:true)
		new Address(country:country, state:'경북',city:'경산시').save(failOnError:true)
		new Address(country:country, state:'경북',city:'경주시').save(failOnError:true)
		new Address(country:country, state:'경북',city:'구미시').save(failOnError:true)
		new Address(country:country, state:'경북',city:'김천시').save(failOnError:true)
		new Address(country:country, state:'경북',city:'문경시').save(failOnError:true)
		new Address(country:country, state:'경북',city:'상주시').save(failOnError:true)
		new Address(country:country, state:'경북',city:'안동시').save(failOnError:true)
		new Address(country:country, state:'경북',city:'영주시').save(failOnError:true)
		new Address(country:country, state:'경북',city:'영천시').save(failOnError:true)
		new Address(country:country, state:'경북',city:'포항시 남구').save(failOnError:true)
		new Address(country:country, state:'경북',city:'포항시 북구').save(failOnError:true)
		new Address(country:country, state:'경북',city:'고령군').save(failOnError:true)
		new Address(country:country, state:'경북',city:'군위군').save(failOnError:true)
		new Address(country:country, state:'경북',city:'봉화군').save(failOnError:true)
		new Address(country:country, state:'경북',city:'성주군').save(failOnError:true)
		new Address(country:country, state:'경북',city:'영덕군').save(failOnError:true)
		new Address(country:country, state:'경북',city:'영양군').save(failOnError:true)
		new Address(country:country, state:'경북',city:'예천군').save(failOnError:true)
		new Address(country:country, state:'경북',city:'울릉군').save(failOnError:true)
		new Address(country:country, state:'경북',city:'울진군').save(failOnError:true)
		new Address(country:country, state:'경북',city:'의성군').save(failOnError:true)
		new Address(country:country, state:'경북',city:'청도군').save(failOnError:true)
		new Address(country:country, state:'경북',city:'청송군').save(failOnError:true)
		new Address(country:country, state:'경북',city:'칠곡군').save(failOnError:true)
		new Address(country:country, state:'전남',city:'광양시').save(failOnError:true)
		new Address(country:country, state:'전남',city:'나주시').save(failOnError:true)
		new Address(country:country, state:'전남',city:'목포시').save(failOnError:true)
		new Address(country:country, state:'전남',city:'순천시').save(failOnError:true)
		new Address(country:country, state:'전남',city:'여수시').save(failOnError:true)
		new Address(country:country, state:'전남',city:'강진군').save(failOnError:true)
		new Address(country:country, state:'전남',city:'고흥군').save(failOnError:true)
		new Address(country:country, state:'전남',city:'곡성군').save(failOnError:true)
		new Address(country:country, state:'전남',city:'구례군').save(failOnError:true)
		new Address(country:country, state:'전남',city:'담양군').save(failOnError:true)
		new Address(country:country, state:'전남',city:'무안군').save(failOnError:true)
		new Address(country:country, state:'전남',city:'보성군').save(failOnError:true)
		new Address(country:country, state:'전남',city:'신안군').save(failOnError:true)
		new Address(country:country, state:'전남',city:'영광군').save(failOnError:true)
		new Address(country:country, state:'전남',city:'영암군').save(failOnError:true)
		new Address(country:country, state:'전남',city:'완도군').save(failOnError:true)
		new Address(country:country, state:'전남',city:'장성군').save(failOnError:true)
		new Address(country:country, state:'전남',city:'장흥군').save(failOnError:true)
		new Address(country:country, state:'전남',city:'진도군').save(failOnError:true)
		new Address(country:country, state:'전남',city:'함평군').save(failOnError:true)
		new Address(country:country, state:'전남',city:'해남군').save(failOnError:true)
		new Address(country:country, state:'전남',city:'화순군').save(failOnError:true)
		new Address(country:country, state:'전북',city:'군산시').save(failOnError:true)
		new Address(country:country, state:'전북',city:'김제시').save(failOnError:true)
		new Address(country:country, state:'전북',city:'남원시').save(failOnError:true)
		new Address(country:country, state:'전북',city:'익산시').save(failOnError:true)
		new Address(country:country, state:'전북',city:'전주시 덕진구').save(failOnError:true)
		new Address(country:country, state:'전북',city:'전주시 완산구').save(failOnError:true)
		new Address(country:country, state:'전북',city:'정읍시').save(failOnError:true)
		new Address(country:country, state:'전북',city:'고창군').save(failOnError:true)
		new Address(country:country, state:'전북',city:'무주군').save(failOnError:true)
		new Address(country:country, state:'전북',city:'부안군').save(failOnError:true)
		new Address(country:country, state:'전북',city:'순창군').save(failOnError:true)
		new Address(country:country, state:'전북',city:'완주군').save(failOnError:true)
		new Address(country:country, state:'전북',city:'임실군').save(failOnError:true)
		new Address(country:country, state:'전북',city:'장수군').save(failOnError:true)
		new Address(country:country, state:'전북',city:'진안군').save(failOnError:true)
		new Address(country:country, state:'제주',city:'제주시').save(failOnError:true)
		new Address(country:country, state:'제주',city:'서귀포시').save(failOnError:true)
		new Address(country:country, state:'충남',city:'계룡시').save(failOnError:true)
		new Address(country:country, state:'충남',city:'공주시').save(failOnError:true)
		new Address(country:country, state:'충남',city:'논산시').save(failOnError:true)
		new Address(country:country, state:'충남',city:'당진시').save(failOnError:true)
		new Address(country:country, state:'충남',city:'보령시').save(failOnError:true)
		new Address(country:country, state:'충남',city:'서산시').save(failOnError:true)
		new Address(country:country, state:'충남',city:'아산시').save(failOnError:true)
		new Address(country:country, state:'충남',city:'천안시 동남구').save(failOnError:true)
		new Address(country:country, state:'충남',city:'천안시 서북구').save(failOnError:true)
		new Address(country:country, state:'충남',city:'금산군').save(failOnError:true)
		new Address(country:country, state:'충남',city:'부여군').save(failOnError:true)
		new Address(country:country, state:'충남',city:'서천군').save(failOnError:true)
		new Address(country:country, state:'충남',city:'예산군').save(failOnError:true)
		new Address(country:country, state:'충남',city:'청양군').save(failOnError:true)
		new Address(country:country, state:'충남',city:'태안군').save(failOnError:true)
		new Address(country:country, state:'충남',city:'홍성군').save(failOnError:true)
		new Address(country:country, state:'충북',city:'제천시').save(failOnError:true)
		new Address(country:country, state:'충북',city:'청주시 상당구').save(failOnError:true)
		new Address(country:country, state:'충북',city:'청주시 흥덕구').save(failOnError:true)
		new Address(country:country, state:'충북',city:'충주시').save(failOnError:true)
		new Address(country:country, state:'충북',city:'괴산군').save(failOnError:true)
		new Address(country:country, state:'충북',city:'단양군').save(failOnError:true)
		new Address(country:country, state:'충북',city:'보은군').save(failOnError:true)
		new Address(country:country, state:'충북',city:'영동군').save(failOnError:true)
		new Address(country:country, state:'충북',city:'옥천군').save(failOnError:true)
		new Address(country:country, state:'충북',city:'음성군').save(failOnError:true)
		new Address(country:country, state:'충북',city:'증평군').save(failOnError:true)
		new Address(country:country, state:'충북',city:'진천군').save(failOnError:true)
		new Address(country:country, state:'충북',city:'청원군').save(failOnError:true)

		
		new ActivityType(name:'청소', type:"Volunteer").save(failOnError:true)
		new ActivityType(name:'미용', type:"Volunteer").save(failOnError:true)
		new ActivityType(name:'의료', type:"Volunteer").save(failOnError:true)
		new ActivityType(name:'보수', type:"Volunteer").save(failOnError:true)
		new ActivityType(name:'기타', type:"Volunteer").save(failOnError:true)
		new ActivityType(name:'물품후원', type:"Sponsored").save(failOnError:true)
		new ActivityType(name:'금액후원', type:"Sponsored").save(failOnError:true)
	}
    def destroy = {
    }
}
